name: HCU unit tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - .github/workflows/hcu_unit_tests.yml
  pull_request:
    branches:
      - main
    paths:
      # The order that you define paths patterns matters:
      # A matching negative pattern (prefixed with !) after a positive match will exclude the path.
      # A matching positive pattern after a negative match will include the path again.
      - "**/*.py"
      # Other entrypoints
      - "!examples/**"
      - "!tests/special_sanity/**"
      - "!verl/trainer/main_*.py"
      - "!verl/trainer/fsdp_sft_trainer.py"
      # Entrypoints
      - .github/workflows/hcu_unit_tests.yml
      - "tests/**test_*.py"
      # Ignore CPU tests
      - "!tests/*_on_cpu.py"

# Cancel jobs on the same ref if a new one is triggered
concurrency:
  group: hcu_unit_tests
  cancel-in-progress: true

# Declare permissions just read content.
permissions:
  contents: read

env:
  GLOG_minloglevel: 3
  PYTHONWARNINGS: "ignore"
  TORCH_CPP_LOG_LEVEL: "fatal"
  TRANSFORMERS_VERBOSITY: "error"
  VLLM_CUDART_SO_PATH: "/opt/dtk/hip/lib/libgalaxyhip.so"

jobs:
  hcu_unit_tests:
    runs-on: 
      - self-hosted
      - bw1000
      - ${{ vars.VERL_HCU_CI_RUNNER_LABEL || 'hcu-ci-unconfigured' }}
    timeout-minutes: 60 # Increase this timeout value as needed
    steps:
      - name: Install the current repository
        run: |
          pip3 install TransferQueue==0.1.7 mlflow
      - name: Check final pip list
        run: |
          pip3 list
      - name: Run all HCU unit tests
        run: |
          pytest -s -x --ignore-glob="*test_special_*.py" tests/
      - name: Testing Megatron KL Loss TP Correctness
        run: |
          torchrun --standalone --nnodes=1 --nproc-per-node=2 tests/utils/test_special_megatron_kl_loss_tp.py
